# Generated by Django 4.1.5 on 2023-02-01 17:16

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('news', '0003_subscription'),
    ]

    operations = [
        migrations.RenameField(
            model_name='postcategory',
            old_name='category_through',
            new_name='categoryThrough',
        ),
        migrations.AddField(
            model_name='category',
            name='subscribers',
            field=models.ManyToManyField(related_name='categories', to=settings.AUTH_USER_MODEL),
        ),
    ]
